host = "0.0.0.0"
port = 8080

secret_key = "your_very_secure_and_long_secret_key_here"
api_key = "your_api_key_here"
admin_username = "admin"
admin_password = "admin"
database_location = "theft-preventer.db"

twilio_account_sid = "your_twilio_account_sid"
twilio_auth_token = "your_twilio_auth_token"
twilio_from_number = "+1234567890"
admin_phone_number = "+0987654321"