version: '3.8'

services:
  theft-preventer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - APP_SECRET_KEY=${APP_SECRET_KEY:-your_default_secret_key}
      - APP_API_KEY=${APP_API_KEY:-your_default_api_key}
      - APP_ADMIN_USERNAME=${APP_ADMIN_USERNAME:-admin}
      - APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD:-password}
      - APP_DATABASE_LOCATION=/app/data/database.sqlite
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data: